name: Static Analysis

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: mypy
      run: uv run -- mypy src/rfantasy_bingo_stats
    - name: pylint
      run: uv run -- pylint -d C,R src/rfantasy_bingo_stats
    - name: black
      run: uv run -- black src/rfantasy_bingo_stats --check
    - name: isort
      run: uv run -- isort src/rfantasy_bingo_stats --check-only
